[package]
name = "data-acquisition"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ms5611-spi = "0.2.0"
embedded-hal = "0.2.6"